import { useRouter } from "next/router";
import Head from "next/head";
import TopCaseStudy from "@/Components/CaseStudy/Top";
import BasicInformationCaseStudy from "@/Components/CaseStudy/BasicInformation";
import DescriptionCaseStudy from "@/Components/CaseStudy/Description";
import GaleryCaseStudy from "@/Components/CaseStudy/Galery";


function CaseStudy() {
    const router = useRouter()
    const name = router.query.name
    return (
        <>
            <Head>
                <title>{name}</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <TopCaseStudy />

            <DescriptionCaseStudy />

            <BasicInformationCaseStudy />

            <GaleryCaseStudy />
        </>
    );
}

/*
    {
        name: string
        shortDescription: string
        description: string
        link: string
        technologies: {name: string, img: string}[] 
        basicInformation: { ??? }[]
        Galery: string[]
    }
*/



export default CaseStudy;